# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160712_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/data'),
        ),
    ]
